### ISSUE TITLE
Re-style mobile navigation

### ISSUE THREAD

**Issue by ttntm** [ttntm/shmsr#1]
Should have some animated open/close icon.

**Comment by SaharHeumesser** [comment]
i would love to have this effect on ''become a patron of my art''
https://codemyui.com/pure-css-text-revealing-animation/

**Comment by ttntm** [comment]
i would love to have a mixture of these 2 effects for my menu botton on mobile version
https://codemyui.com/hamburger-menu-to-exit-animation/
https://codemyui.com/toggle-menu-that-slides-from-the-top/

**Comment by SaharHeumesser** [comment]
i will explain to you at home

**Comment by SaharHeumesser** [comment]
i realy like this one: https://codemyui.com/toggle-menu-that-slides-from-the-top/

**Comment by SaharHeumesser** [comment]
this is also a good example of the menu effect: http://mindful-women.com/story/

**Comment by SaharHeumesser** [comment]
tnx well done- we can close this issue now
