### ISSUE TITLE
Resize/restyle download button

### ISSUE THREAD

**Issue by SaharHeumesser** [ttntm/shmsr#10]
download button should get smaller:_ same as back to blog button

**Comment by ttntm** [comment]
It's sized the same as the "Back to blog" button now.

**Comment by SaharHeumesser** [comment]
it is smaller but still not looking the same. sont style and border is different.
please make it look like same as back to blog button
![image](https://user-images.githubusercontent.com/53819992/62775124-13712e00-baa7-11e9-98e9-56ef2a4613dc.png)

**Comment by ttntm** [comment]
button changed, so nothing to do here.

**Comment by SaharHeumesser** [comment]
done
