### ISSUE TITLE
image display's effects

### ISSUE THREAD

**Issue by SaharHeumesser** [ttntm/shmsr#12]
At the very buttom of this blog there are instagram photos and they have a effect on them. i would love to change the effect of my portfoilio's image and my shop's image into something like that.
 can you do it? i mean to remove the green bottun and instead add the frame! and
also i want to keep the effect that the photo pops up and the transparecy should be a bit less so the image under it is a bit more visible. right now it turns to almost white square.

**Comment by ttntm** [comment]
A link to that example would be good, I think you forgot to paste that.

**Comment by SaharHeumesser** [comment]
https://foreveramber.co.uk/

**Comment by SaharHeumesser** [comment]
ALSO A COOL IDEA. https://codepen.io/chrisdothtml/full/OVmgwK

**Comment by SaharHeumesser** [comment]
this as well is a great example:https://rynfrankdesign.co.uk/portfolio/

**Comment by ttntm** [comment]
Done for the time being?

**Comment by SaharHeumesser** [comment]
done
