### ISSUE TITLE
heading fonts sizes

### ISSUE THREAD

**Issue by SaharHeumesser** [ttntm/shmsr#15]
please tell me the size of the headings in pxl.
i only know the body text is 16 pxl.
h1 ?
h2 ?
h3?
h4 ?
h5 ?
h6 ?

**Comment by ttntm** [comment]
h1: 32px
h2: 28px
h3: 24px
h4: 20px
h5: 18px
h6: 17px

**Comment by SaharHeumesser** [comment]
PLEASE MAKE THEN IN THIS WAY.
body text : 15 pxl
h1 : 45 pxl
h2 : 40 pxl
h3 : 35 pxl
h4 : 30 pxl
h5 : 25 pxl
h6 : 20 pxl

**Comment by SaharHeumesser** [comment]
this will be in the info guide so i am closing it
