### ISSUE TITLE
Implement comments for blog posts

### ISSUE THREAD

**Issue by ttntm** [ttntm/shmsr#16]
See: 
- https://gohugo.io/content-management/comments/
- https://staticman.net/docs/
- https://discourse.gohugo.io/t/button-to-show-disqus-comments/17418

**Comment by VincentTam** [comment]
> See:
> 
> * https://gohugo.io/content-management/comments/
> * https://staticman.net/docs/
> * https://discourse.gohugo.io/t/button-to-show-disqus-comments/17418

Hi, this is the maintainer of @staticmanlab.  The second link is outdated.  Staticman's docs doesn't cover v3.  The v2 no longer works, as reported in https://github.com/eduardoboucas/staticman/issues/306.

**Comment by ttntm** [comment]
Still checking, first test of https://css-tricks.com/jamstack-comments/ has failed.

Alternative might be: https://www.talkyard.io/blog-comments
But it's 1. not free and 2. (maybe) limited in terms of visual customization...

**Comment by VincentTam** [comment]
> Alternative might be: https://www.talkyard.io/blog-comments
> But it's 1. not free and 2. (maybe) limited in terms of visual customization...

In constrast, Staticman is free and flexible in terms of visual customization.  Examples:

1. My blog: https://lstu.fr/3s
2. Another blog: https://zcrc.me

**Comment by ttntm** [comment]
Thanks @VincentTam I just had another look at https://staticman.net :)

Just one question: do you have any sort of data processing agreement/privacy policy regarding the use of the Staticman API? 

I suppose the API would collect/process the submitted fields plus the submitter's IP addresses at least, which would make that relevant for the GDPR here in the EU.

**Comment by VincentTam** [comment]
> Just one question: do you have any sort of data processing agreement/privacy policy regarding the use of the Staticman API?
> I suppose the API would collect/process the submitted fields plus the submitter's IP addresses at least, which would make that relevant for the GDPR here in the EU.

Related: https://github.com/eduardoboucas/staticman/issues/277

**Comment by ttntm** [comment]
Implemented my own working example from https://github.com/ttntm/hugo-comments now, it's enough to get started with.
