### ISSUE TITLE
Add effect on patreon text

### ISSUE THREAD

**Issue by SaharHeumesser** [ttntm/shmsr#2]
i would love to have this effect on ''become a patron of my art''
https://codemyui.com/pure-css-text-revealing-animation/

**Comment by SaharHeumesser** [comment]
i would love to have search button and  this effect for it
https://codemyui.com/search-icon-search-bar-morph/

**Comment by ttntm** [comment]
This only works for text, not images. The Patreon button is an image currently.

**Comment by SaharHeumesser** [comment]
please read again!
i never said patreon bottun! the text that shows on top of the bottun and says: ''become a patron of my art''

**Comment by SaharHeumesser** [comment]
why did you close this? you still didnt do it and if you close them before being done i will forget and we will have the same converstaion in couples of weeks.

**Comment by SaharHeumesser** [comment]
why did you close this? you still didnt do it and if you close them before being done i will forget and we will have the same converstaion in couples of weeks.

**Comment by SaharHeumesser** [comment]
I still want this effect: [https://codemyui.com/pure-css-text-revealing-animation/](url)

**Comment by SaharHeumesser** [comment]
this one really fits
https://codemyui.com/creepy-squiggly-text-effect-with-svg/[https://codemyui.com/creepy-squiggly-text-effect-with-svg/](url)

**Comment by ttntm** [comment]
I did the  revealing one for now, the squiggly text was terrible in terms of browser support and performance.

**Comment by SaharHeumesser** [comment]
a ok
