### ISSUE TITLE
please add this under the currently reading

### ISSUE THREAD

**Issue by SaharHeumesser** [ttntm/shmsr#22]
![image](https://user-images.githubusercontent.com/53819992/63588299-7635ef80-c5a6-11e9-9981-607ac793fc47.png)

**Comment by SaharHeumesser** [comment]
please change the text ''check previous books'' to ''MY READING LIST''

**Comment by ttntm** [comment]
Was added, together with a reading list.

**Comment by SaharHeumesser** [comment]
done
