### ISSUE TITLE
add pinterest features

### ISSUE THREAD

**Issue by SaharHeumesser** [ttntm/shmsr#24]
1. [https://help.pinterest.com/en/business/article/save-button](url)
2. [https://about.pinterest.com/en/browser-button-confirmation-page](url)

**Comment by ttntm** [comment]
#1 is not going to happen 
#2 is up to each and every user themselves, so we don't actually have to do anything here

**Comment by ttntm** [comment]
Not quite possible at the moment. If anything good comes up in the future, we'll revisit this topic.
