### ISSUE TITLE
© little change

### ISSUE THREAD

**Issue by SaharHeumesser** [ttntm/shmsr#28]
© Sahar Heumesser 2019, all rights reserved |  Imprint | Developed by ttntm | Designed by Sahar Heumesser Design Studio

**Comment by SaharHeumesser** [comment]
with links to our website on our name on our name of course

**Comment by ttntm** [comment]
done as 2 lines 'cause it looked better

**Comment by SaharHeumesser** [comment]
ok tnx bit can you also change all dash and commas to the vertical line plz.
© Sahar Heumesser 2019 | all rights reserved | Privacy Policy | Imprint
Designed by Sahar Heumesser Design Studio | Code by ttntm

**Comment by ttntm** [comment]
that's done
