### ISSUE TITLE
Add newsletter subscription

### ISSUE THREAD

**Issue by SaharHeumesser** [ttntm/shmsr#5]
for newslwtter subscribe button i like it to turn to thank you boton like thi link but the boton shoul look like my own bottons
https://codemyui.com/rounded-button-email-notification/

**Comment by ttntm** [comment]
There's no usable snippet in hte link provided.
Also, in order to comply with the GDPR, you have to do double opt-in these days. 
Therefore, after clicking "Subcribe", the user will inevitably leave your site and never see the "Thanks you" part.
Button to form should be possible though.

**Comment by ttntm** [comment]
Implemented & tested.

**Comment by SaharHeumesser** [comment]
done
