### ISSUE TITLE
Readjust all heading sizes/styles

### ISSUE THREAD

**Issue by ttntm** [ttntm/shmsr#7]

**Comment by SaharHeumesser** [comment]
body text : 15 pxl
h1 : 45 pxl
h2 : 40 pxl
h3 : 35 pxl
h4 : 30 pxl
h5 : 25 pxl
h6 : 20 pxl

**Comment by ttntm** [comment]
check https://shrwip.netlify.com/ it looks rather weird and improportionally oversized that way.

**Comment by SaharHeumesser** [comment]
tnx well done- we can close this issue now
