### ISSUE TITLE
Add shortcode to open blog post links in new tab 

### ISSUE THREAD

**Issue by SaharHeumesser** [ttntm/shmsr#8]
by clicking on links i want the links to open in a new tab

**Comment by ttntm** [comment]
Using `{{< link-ext "LinkText" "LinkURL" >}}` you can create external links now.

**Comment by SaharHeumesser** [comment]
it seems you already solved it, or should i write this line every time i make a link?

**Comment by ttntm** [comment]
this is the syntax of creating an external = new tab link. so yes, whenever you want to make one of these, that's what you should do.

**Comment by SaharHeumesser** [comment]
cool, tnx
i am collecting all the syntax that you are sending me in a file :D
