### ISSUE TITLE
ASAP-Amazon

### ISSUE THREAD

**Issue by SaharHeumesser** [ttntm/shmsr#9]
plz put this somewhere in the website:
“As an Amazon Associate I earn from qualifying purchases.”

**Comment by ttntm** [comment]
You can do that yourself, simply edit the "Imprint" page under the "Pages" node in forestry.

**Comment by SaharHeumesser** [comment]
ok i will. there are 4 parts in there unde which one should i put it?
1.Liability for the content of this website
2.Liability for links on this website
3.Copyright notice
4.Picture copyright
